baseURL = 'https://ia.loria.fr/frugalday/'
languageCode = 'fr-fr'
title = 'Journée frugalité en TAL et ML'
theme = 'dettheme'

paginate = '4' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = '' # <- Your GA-4
disqusShortname = '' # <- Get form here : https://disqus.com

[markup.goldmark.renderer]
unsafe= true

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Journée Frugalité en TAL et ML'
	mainSections = 'posts'
    [[author]]
        name = 'Christophe Cerisara'
        bio = 'CNRS researcher'
        avatar = '/images/nasa-astronaut-unsplash.jpg'
        twitter = ''

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 15
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 20
	[[menu.main]]
		name = 'Taxonomy'
		pageRef = '/tags/nlp/'
		weight = 25

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'
